### ISSUE TITLE
Stubbing Event Emitters

### ISSUE THREAD

**Issue by cookie-bytes** [REAANDREW/deride#36]
Hi,

As requested by James.
Currently trying to test that we would handle the two different outcomes from restler correctly by using a deride stub.
However struggling to get the event emitters to work?? 

<pre><code>self.read = function(id, callback) {
	restler
		.get(url)
		.on('success', function(person) {
			console.log('sucess');                                                             
			return callback(null, person);
		})
		.on('fail', function(err) { 
			console.log('fail');
			return callback(err, null);                                                        
		});       

}
</code></pre>

**Comment by jamlen** [comment]
So this turns out to be a bit more specific to the `restify` library, in that it appears it doesn't do a method chaining from the `get` method, rather that it returns the event emitter.

The working example of this is:
```javascript
var eventEmitter = new events.EventEmitter();
var restler = deride.wrap(require('restler'));
restler.setup.get.toDoThis(function(url) {
    console.log('get called', url);
    setTimeout(function() {
        eventEmitter.emit('success', {
            message: 'dummy'
        });
        url.should.eql('http://something');
    }, 5);
    return eventEmitter;
});


restler.get('http://something')
    .on('success', function(data) {
        should(data).not.be.null;
        done();
    });
```
The `setTimeout` was necessary just to allow the wiring up of the event subscriber before returning.
